// tools/models/registry.cjs
// WP-8 model registry + per-model confirmation matrices (audit Section 0,
// Gap 3.2, Gap 3.4, Gap 1.4, Gap 4.5).
//
// A model is a RECIPE, not a dish with a rank. Each entry carries:
//   timeWindows         — when this recipe may be cooked (NY hours, end-exclusive)
//   intrinsicDirection  — what the model MEANS by its mechanics
//   sequence            — the confirmation matrix; EVERY step must pass
//   purgeRequired       — eligibility demands a liquidity purge (fuel collected)
//
// The decision path is eligibility + sequence only. No numeric rank exists —
// a model is either COMPLETE or it is nothing. If exactly one model is complete
// → SETUP COMPLETE. If zero or several → NO TRADE (ties resolve by tier, then
// by proximity to a draw, never by multiplying confidences).

const { steps } = require("./steps.cjs");
const fs = require("fs");
const path = require("path");

// WP-15: Shadow backtest weights — models with proven win rates get tiebreaker preference.
// Generated by tools/shadow_backtest.cjs --feed-tiebreaker after 20+ days of shadow data.
let shadowWeights = {};
try {
  const weightsPath = path.resolve(__dirname, "../../shared/shadow_backtest/tiebreaker_weights.json");
  if (fs.existsSync(weightsPath)) {
    shadowWeights = JSON.parse(fs.readFileSync(weightsPath, "utf8")).weights || {};
  }
} catch { /* shadow data not yet available */ }

// WP-16: ML classifier weights — probabilistic model performance from gradient-boosted trees.
// Generated by python tools/train_classifier.py from historical feature matrix.
// Provides per-model win rates and P(win) calibration for tie-breaking.
let mlWeights = {};
try {
  const mlPath = path.resolve(__dirname, "../../shared/training/classifier_weights.json");
  if (fs.existsSync(mlPath)) {
    const ml = JSON.parse(fs.readFileSync(mlPath, "utf8"));
    mlWeights = ml.models || {};
  }
} catch { /* ML weights not yet available */ }

const MODELS = [
  // ── Tier 1 ────────────────────────────────────────────────────────────
  { id: "mmxm_sell", name: "MMXM Sell Model", tier: 1, timeWindows: null,
    intrinsicDirection: "SELL", purgeRequired: true,
    sequence: ["killzone", "sweep", "ob", "mss", "smt"],
    description: "Market Maker Expansion — distribution: sell the rally after a purge." },
  { id: "mmxm_buy", name: "MMXM Buy Model", tier: 1, timeWindows: null,
    intrinsicDirection: "BUY", purgeRequired: true,
    sequence: ["killzone", "sweep", "ob", "mss", "smt"],
    description: "Market Maker Expansion — accumulation: buy the dip after a purge." },
  { id: "silver_bullet", name: "Silver Bullet", tier: 1,
    timeWindows: [{ label: "London SB", start: 3, end: 4 }, { label: "NY AM SB", start: 10, end: 11 }, { label: "NY PM SB", start: 14, end: 15 }],
    intrinsicDirection: "narrative", purgeRequired: true,
    sequence: ["sweep", "reversal", "mss", "fvg", "tethered_array"],
    description: "One candle, one displacement, one window — the scalp in the SB window. NY-AM/PM deliveries must tether to the 7-9AM canvas." },
  { id: "ote_institutional_ob", name: "OTE + Institutional OB", tier: 1, timeWindows: null,
    intrinsicDirection: "narrative", purgeRequired: false,
    sequence: ["killzone", "ob", "ote", "array_mitigated"],
    description: "Entry at OTE of the displacement leg, back at the institutional OB." },
  { id: "turtle_soup", name: "Turtle Soup", tier: 1, timeWindows: null,
    intrinsicDirection: "counter-sweep", purgeRequired: true,
    sequence: ["killzone", "htf_ranging", "sweep", "reversal", "mss", "displacement"],
    description: "Failed breakout — fade the sweep once price closes back inside." },
  { id: "unicorn_ote_fvg", name: "Unicorn (OTE+FVG)", tier: 1, timeWindows: null,
    intrinsicDirection: "narrative", purgeRequired: false,
    sequence: ["killzone", "ob", "fvg", "ote"],
    description: "FVG at OTE — confluence of imbalance and the ideal retracement." },
  { id: "breaker_block", name: "Breaker Block", tier: 1, timeWindows: null,
    intrinsicDirection: "narrative", purgeRequired: false,
    sequence: ["killzone", "ob", "reversal", "mss"],
    description: "The OB that broke and flipped — trade the flip after the reversal holds." },

  // ── Tier 2 ────────────────────────────────────────────────────────────
  { id: "ifvg_scale_in", name: "IFVG Scale-In", tier: 2, timeWindows: null,
    intrinsicDirection: "narrative", purgeRequired: true,
    sequence: ["killzone", "sweep", "reversal", "mss", "ifvg_present"],
    description: "Inversion FVG as dynamic support/resistance after sweep+reversal. Initial entry inside bias-aligned IFVG; scale in at deep/CE levels on retest. ICT: High-Resistance Liquidity Run Conditions." },
  { id: "scob", name: "SCOB", tier: 2, timeWindows: null,
    intrinsicDirection: "narrative", purgeRequired: false,
    sequence: ["killzone", "ob", "fvg", "displacement"],
    description: "Single Candle Order Block — OB + FVG + displacement on the same leg." },
  { id: "two_fvg", name: "2FVG Entry", tier: 2, timeWindows: null,
    intrinsicDirection: "narrative", purgeRequired: false,
    sequence: ["killzone", "fvg", "sweep"],
    description: "Two consecutive unmitigated FVGs — expansion fuel stacked." },
  { id: "judas_swing", name: "Judas Swing", tier: 2,
    timeWindows: [{ label: "London open", start: 2, end: 3 }, { label: "NY open", start: 8, end: 9 }],
    intrinsicDirection: "fade-first-move", purgeRequired: true,
    sequence: ["sweep", "mss"],
    description: "The fake session-open swing — fade the first move after the sweep." },
  { id: "asian_range_breakout", name: "Asian Range Breakout", tier: 2,
    timeWindows: [{ label: "Asia", start: 20, end: 2 }],
    intrinsicDirection: "breakout", purgeRequired: true,
    sequence: ["sweep", "ob"],
    description: "Break of the Asian range in the direction of the narrative." },
  { id: "nwog_ndog", name: "NWOG/NDOG", tier: 2, timeWindows: null,
    intrinsicDirection: "narrative", purgeRequired: false,
    sequence: ["killzone", "ob"],
    description: "Weekly/daily opening gap plays — draw on the gap fill." },

  // ── Tier 3 — Situational / time-based ────────────────────────────────
  { id: "mitigation_block", name: "Mitigation Block", tier: 3, timeWindows: null,
    intrinsicDirection: "narrative", purgeRequired: false,
    sequence: ["killzone", "ob", "array_mitigated"],
    description: "The OB that was tagged but not broken — entry on the mitigation." },
  { id: "rejection_block", name: "Rejection Block", tier: 3, timeWindows: null,
    intrinsicDirection: "counter-sweep", purgeRequired: false,
    sequence: ["killzone", "ob", "reversal"],
    description: "The OB that HELD — a rejection wick at the array, then reversal." },
  { id: "london_hunt_ifvg", name: "London Hunt + IFVG", tier: 3,
    timeWindows: [{ label: "London Hunt", start: 7, end: 8 }],
    intrinsicDirection: "narrative", purgeRequired: true,
    sequence: ["lecture2_hunt_swept", "lecture2_mss", "lecture2_ready"],
    description: "07:00 NY hunt of relative equal levels → IFVG CE entry." },
  { id: "ndog_nwog_news", name: "NDOG/NWOG News Model", tier: 3,
    timeWindows: [{ label: "News", start: 8, end: 10 }],
    intrinsicDirection: "narrative", purgeRequired: true,
    sequence: ["lecture4_gap_draw", "sweep", "lecture4_mss", "lecture4_ready", "tethered_array"],
    description: "News gap draw — MSS at the gap cluster, entry at the breaker/CE. Purge gate: the gap must be swept before it is a draw (WP-12 5.3). Post-9:01 entries tether to the 7-9AM canvas." },
  { id: "raid_0830", name: "08:30 Liquidity Raid Model", tier: 3,
    timeWindows: [{ label: "Raid", start: 8, end: 10 }],
    intrinsicDirection: "narrative", purgeRequired: true,
    sequence: ["lecture1_formation", "lecture1_raid", "lecture1_mss", "lecture1_ready", "tethered_array"],
    description: "Post-08:30 raid of the pre-open equal levels → PD array entry. Post-9:01 entries tether to the 7-9AM canvas." },

  // ── Tier 3 — NY Lunch Reversal (Prev-Day Carry-Forward) ──────────────
  // ICT CPI Day Video (2026): New PDA — prior-day lunch inefficiency before
  // the liquidity sweep carried forward. BISI → bearish reversal (short),
  // SIBI → bullish reversal (long). Valid all NY sessions — the entry
  // happens NEXT day when price returns to the carried level.
  { id: "ny_lunch_reversal_short", name: "NY Lunch Reversal (Short)", tier: 3,
    timeWindows: [{ label: "NY AM", start: 8, end: 11 }, { label: "NY PM", start: 13, end: 16 }],
    intrinsicDirection: "SELL", purgeRequired: false,
    sequence: ["prev_day_lunch_sweep", "prev_day_bisi", "price_enters_lunch_inefficiency", "mss"],
    description: "Prior day NY lunch BISI carried forward → price enters zone → complex reversal SHORT. ICT: 'If it trades up into it, it can set the tone for a shorting opportunity.'" },
  { id: "ny_lunch_reversal_long", name: "NY Lunch Reversal (Long)", tier: 3,
    timeWindows: [{ label: "NY AM", start: 8, end: 11 }, { label: "NY PM", start: 13, end: 16 }],
    intrinsicDirection: "BUY", purgeRequired: false,
    sequence: ["prev_day_lunch_sweep", "prev_day_sibi", "price_enters_lunch_inefficiency", "mss"],
    description: "Prior day NY lunch SIBI carried forward → price enters zone → complex reversal LONG. ICT: 'Reverse it for going long.'" },
];

const ALL_STEP_NAMES = new Set(Object.keys(steps));

function inModelWindow(model, hour) {
  if (!model.timeWindows || model.timeWindows.length === 0) return { pass: true, detail: "any window" };
  const h = Number.isFinite(hour) ? ((hour % 24) + 24) % 24 : -1;
  for (const w of model.timeWindows) {
    const open = (w.start <= w.end) ? (h >= w.start && h < w.end) : (h >= w.start || h < w.end);
    if (open) return { pass: true, detail: `${w.label} (${w.start}:00-${w.end}:00 NY)` };
  }
  return { pass: false, detail: `outside ${model.timeWindows.map(w => w.label).join(" / ")}` };
}

function fadeDirection(ctx) {
  if (ctx.lastSweepType === "BSL") return "SELL"; // highs raided → fade down
  if (ctx.lastSweepType === "SSL") return "BUY";  // lows raided → fade up
  return null;
}

function directionAligned(model, ctx) {
  const d = model.intrinsicDirection;
  if (d === "narrative") return ctx.bias && ctx.bias !== "neutral";
  if (d === "SELL") return ctx.bias === "bearish";
  if (d === "BUY") return ctx.bias === "bullish";
  if (d === "counter-sweep" || d === "fade-first-move") {
    const fade = fadeDirection(ctx);
    return fade === "SELL" ? ctx.bias === "bearish" : fade === "BUY" ? ctx.bias === "bullish" : false;
  }
  return true;
}

function directionDetail(model, ctx) {
  const d = model.intrinsicDirection;
  if (d === "narrative") return ctx.bias && ctx.bias !== "neutral" ? `narrative ${ctx.bias.toUpperCase()}` : "narrative neutral — no direction";
  if (d === "SELL" || d === "BUY") return `intrinsic ${d} vs bias ${(ctx.bias || "neutral").toUpperCase()}`;
  const fade = fadeDirection(ctx);
  return `fade ${fade || "unknown-sweep"} vs bias ${(ctx.bias || "neutral").toUpperCase()}`;
}

// Eligibility: window + intrinsic direction + purge. All three are booleans.
function eligibilityOf(model, ctx) {
  const win = inModelWindow(model, ctx.hour);
  const dir = { pass: directionAligned(model, ctx), detail: directionDetail(model, ctx) };
  const purge = { pass: !model.purgeRequired || !!ctx.hasSweep, detail: model.purgeRequired ? (ctx.hasSweep ? "purge present" : "purge required but absent") : "no purge prerequisite" };
  const eligible = win.pass && dir.pass && purge.pass;
  return { win, dir, purge, eligible };
}

// Run every step in the model's confirmation matrix. Each step is a boolean gate.
function sequenceOf(model, ctx) {
  return model.sequence.map(name => {
    const fn = steps[name];
    if (!fn) return { name, pass: false, detail: `unknown sequence step "${name}" (not in vocabulary)` };
    const r = fn(ctx) || { pass: false, detail: "step returned no verdict" };
    return { name, pass: !!r.pass, detail: r.detail };
  });
}

// ═══ WP-17: Pool-First Architecture — model scoring against the locked draw ═══
// ICT teaches: the pool IS the trade idea. Models are evaluated against the
// locked liquidity draw, not against the entire chart. A model that completes
// but targets an unrelated pool is noise. A model that targets the locked pool
// is THE trade.
function poolProximity(model, ctx) {
  const pc = ctx.poolContext;
  if (!pc) return { score: 1.0, detail: "No pool context — all models pass" };

  // Determine which direction this model implies
  const dir = directionOf(model, ctx);
  if (!dir) return { score: 0.5, detail: "Model has no clear direction — neutral" };

  // If a pool IS locked, models must target it or be penalized
  if (pc.locked && pc.lockedDirection) {
    const matchesLocked = dir === pc.lockedDirection;
    if (matchesLocked) {
      return { score: 2.0, detail: `✅ Targets locked ${pc.lockedDirection} pool — PRIMARY`, boost: pc.directionBoost || 1.3 };
    } else {
      return { score: 0.3, detail: `❌ ${dir} vs locked ${pc.lockedDirection} pool — COUNTER`, penalty: true };
    }
  }

  // No pool locked yet — score by proximity to the highest-priority unraided pool
  const sessions = pc.sessions || {};
  // Get pools that have been raided (fuel collected) in priority order
  const raidedPools = [];
  for (const key of ["pm", "london", "openingGap", "lunch"]) {
    const s = sessions[key];
    if (s && s.raided) raidedPools.push({ ...s, key });
  }

  // Models targeting a raided pool (fuel is there) get a boost
  const poolDirections = [];
  if (raidedPools.length > 0) {
    // Raided lows → SSL swept → bullish reversal expected → BUY models preferred
    // Raided highs → BSL swept → bearish reversal expected → SELL models preferred
    for (const p of raidedPools) {
      if (p.low !== undefined && p.low !== null) poolDirections.push("BUY");
      if (p.high !== undefined && p.high !== null) poolDirections.push("SELL");
    }
    const uniqueDirs = [...new Set(poolDirections)];
    if (uniqueDirs.includes(dir)) {
      return { score: 1.5, detail: `✅ ${dir} targets raided pools (${raidedPools.map(p => p.label).join(', ')})`, boost: 1.2 };
    }
  }

  return { score: 1.0, detail: "No pool constraint — neutral" };
}

function evaluateModel(model, ctx) {
  const elig = eligibilityOf(model, ctx);
  const sequence = sequenceOf(model, ctx);
  const pool = poolProximity(model, ctx);
  const complete = elig.eligible && sequence.every(s => s.pass);
  return {
    id: model.id,
    name: model.name,
    tier: model.tier,
    timeWindows: model.timeWindows,
    intrinsicDirection: model.intrinsicDirection,
    purgeRequired: model.purgeRequired,
    sequence,
    complete,
    pool,
    gateTrace: {
      window: elig.win,
      direction: elig.dir,
      purge: elig.purge,
      sequence,
      pool,
    },
  };
}

// Helper: effective direction for pool-targeting
function directionOf(model, ctx) {
  const d = model.intrinsicDirection;
  if (d === "SELL") return "SELL";
  if (d === "BUY") return "BUY";
  if (d === "counter-sweep" || d === "fade-first-move") {
    return fadeDirection(ctx);
  }
  if (ctx.bias === "bearish") return "SELL";
  if (ctx.bias === "bullish") return "BUY";
  return ctx.poolContext?.dailyBias === "bearish" ? "SELL" :
         ctx.poolContext?.dailyBias === "bullish" ? "BUY" : null;
}

function tieBreak(a, b, ctx) {
  // ═══ WP-17: Pool-First — locked pool takes absolute priority ═══
  // When a session pool is RAIDED + MSS CONFIRMED, that pool IS the trade.
  // Models targeting it win automatically. Models opposing it are discarded.
  if (ctx.poolContext?.locked) {
    const aPool = a.pool || poolProximity({ name: a.name, intrinsicDirection: a.intrinsicDirection, tier: a.tier }, ctx);
    const bPool = b.pool || poolProximity({ name: b.name, intrinsicDirection: b.intrinsicDirection, tier: b.tier }, ctx);
    // Penalty models (wrong direction) always lose
    if (aPool.penalty && !bPool.penalty) return 1;
    if (!aPool.penalty && bPool.penalty) return -1;
    // Higher pool score wins
    if (aPool.score !== bPool.score) return aPool.score > bPool.score ? -1 : 1;
  }
  // WP-15: Killzone primacy — time-windowed models that are currently ACTIVE
  // beat always-on (null window) models of the same tier. ICT teaches that the
  // killzone IS the signal — Silver Bullet in the SB window is THE trade.
  const aWindowed = !!(a.timeWindows && a.timeWindows.length > 0);
  const bWindowed = !!(b.timeWindows && b.timeWindows.length > 0);
  // Check if either model's window is currently active
  const aNow = aWindowed && a.timeWindows.some(w => {
    const h = ((ctx.hour % 24) + 24) % 24;
    return w.start <= w.end ? h >= w.start && h < w.end : h >= w.start || h < w.end;
  });
  const bNow = bWindowed && b.timeWindows.some(w => {
    const h = ((ctx.hour % 24) + 24) % 24;
    return w.start <= w.end ? h >= w.start && h < w.end : h >= w.start || h < w.end;
  });
  // Active window beats inactive window
  if (aNow && !bNow) return -1;
  if (!aNow && bNow) return 1;
  // Both active or both inactive: windowed beats always-on
  if (aWindowed && !bWindowed) return -1;
  if (!aWindowed && bWindowed) return 1;
  // Both windowed or both always-on: higher tier first
  if (a.tier !== b.tier) return a.tier - b.tier;
  // Shadow backtest weights: models with proven >50% EOD win rate beat unproven models
  const aShadow = parseFloat(shadowWeights[a.name]?.boost) || 1.0;
  const bShadow = parseFloat(shadowWeights[b.name]?.boost) || 1.0;
  if (aShadow !== bShadow) return aShadow > bShadow ? -1 : 1;

  // WP-16: ML classifier weights — empirical win rates from gradient-boosted trees
  const aML = mlWeights[a.name];
  const bML = mlWeights[b.name];
  const aWR = aML?.win_rate_pct || 0;
  const bWR = bML?.win_rate_pct || 0;
  if (aWR !== bWR) return aWR > bWR ? -1 : 1;  // higher empirical WR wins

  return 0;
}

// WP-16: Bayesian model weight — uses Beta posterior with weak prior centered
// at 50% (no edge). As samples accumulate, the posterior converges to the
// empirical win rate. The blend weight is precision-weighted: when the posterior
// is wide (high uncertainty), the ML is downweighted. When tight (many samples
// with consistent results), the ML dominates.
//
// Beta(α=5+W, β=5+L) — prior of 5 wins + 5 losses = 50% with 10 pseudo-samples.
// After 14W/28L: posterior mean = (5+14)/(10+42) = 19/52 = 36.5%
// After 100W/200L: posterior mean → 35%, but with much tighter variance.
function bayesianWR(modelName) {
  const ml = mlWeights[modelName];
  if (!ml || !ml.samples || ml.samples < 3) return null;

  const wins = ml.wins || Math.round((ml.win_rate_pct || 0) / 100 * ml.samples);
  const losses = ml.samples - wins;
  const priorWins = 5, priorLosses = 5;               // weak prior: 50% WR, 10 pseudo-samples
  const alpha = priorWins + wins;
  const beta = priorLosses + losses;
  const posteriorMean = alpha / (alpha + beta);         // Bayesian estimate
  const posteriorVar = (alpha * beta) / ((alpha + beta) ** 2 * (alpha + beta + 1));
  const posteriorSD = Math.sqrt(posteriorVar);

  // Precision: how much we trust the ML. Two factors:
  // 1. Sample-size factor: log scale, asymptotes to 1.0 at ~200 samples
  // 2. Variance factor: wide posterior → lower precision (uncertain outcomes)
  const logFactor = Math.min(1.0, Math.log(ml.samples + 1) / Math.log(200));
  const varianceFactor = Math.max(0.1, 1.0 - posteriorSD * 3); // SD=0 → 1.0, SD=0.15 → 0.55
  const precision = Math.min(1.0, logFactor * varianceFactor);

  return {
    posteriorMean,
    posteriorSD,
    alpha,
    beta,
    samples: ml.samples,
    rawWR: (ml.win_rate_pct || 0) / 100,
    precision: Math.round(precision * 1000) / 1000,
    logFactor: Math.round(logFactor * 1000) / 1000,
    varianceFactor: Math.round(varianceFactor * 1000) / 1000,
  };
}

function modelWeight(model) {
  const tierW = model.tier === 1 ? 3 : model.tier === 2 ? 2 : 1;
  const bayes = bayesianWR(model.name);
  if (!bayes) return tierW;

  // Precision-weighted blend: more data + lower variance → more ML influence
  const mlInfluence = bayes.precision;
  const tierInfluence = 1.0 - mlInfluence;
  const perfScore = bayes.posteriorMean * 5; // 0-5 scale from Bayesian WR
  return tierW * tierInfluence + perfScore * mlInfluence;
}

// The trade direction a model IMPLIES in the current context — used to bucket
// complete AND partial models by direction for confluence (same-direction models
// stack; opposite-direction models are counter-confluence, never stacked).
function effectiveDirection(model, ctx) {
  const d = model.intrinsicDirection;
  if (d === "SELL") return "SELL";
  if (d === "BUY") return "BUY";
  if (d === "counter-sweep" || d === "fade-first-move") return fadeDirection(ctx);
  // narrative / breakout follow the governing bias
  if (ctx.bias === "bearish") return "SELL";
  if (ctx.bias === "bullish") return "BUY";
  return null;
}

// Direction-aware confluence. Only sequence-step failures count as "partial"
// support — models ineligible on window/purge are excluded, and models whose
// intrinsic direction opposes the primary count toward the opposite bucket
// (they degrade confidence; they never get stacked on the wrong side).
function confluenceOf(results, ctx) {
  const out = {
    BUY: { complete: 0, partial: 0, weight: 0, models: [] },
    SELL: { complete: 0, partial: 0, weight: 0, models: [] },
  };
  for (const r of results) {
    const model = MODELS.find(m => m.id === r.id);
    if (!model) continue;
    const dir = effectiveDirection(model, ctx);
    if (!dir) continue;
    const el = r.gateTrace;
    // Window/purge ineligible → contributes nothing (not a partial setup).
    if (!el.window.pass || !el.purge.pass) continue;
    const bucket = out[dir];
    const total = r.sequence.length;
    const passed = r.sequence.filter(s => s.pass).length;
    if (r.complete) {
      bucket.complete += 1;
      bucket.weight += modelWeight(model);           // WP-16: ML-augmented weight
    } else {
      // Partial credit = fraction of sequence steps actually confirmed.
      bucket.partial += 1;
      bucket.weight += modelWeight(model) * (total ? passed / total : 0);
    }
    bucket.models.push({ id: r.id, complete: r.complete, seq: total ? passed / total : 0 });
  }
  return out;
}

function confidenceOf(primaryDir, confluence) {
  const opp = primaryDir === "SELL" ? "BUY" : "SELL";
  const same = confluence[primaryDir]?.weight || 0;
  const against = confluence[opp]?.weight || 0;
  const total = same + against;
  if (total <= 0) return 0.5;
  const c = same / total;
  return Math.max(0.05, Math.min(0.97, Math.round(c * 100) / 100));
}

// Full registry evaluation. Verdict is a boolean: exactly one complete model —
// BUT complete models in the SAME direction reinforce (stacking confluence) and
// still resolve to SETUP COMPLETE; complete models in OPPOSITE directions are a
// genuine conflict and fail closed to NO TRADE. Partial models only grade
// confidence — they can never authorize a trade.
function runRegistry(ctx) {
  // WP-15: scalpOnly mode — Step 4 (Re-accumulation) gates to tier 2+ scalp models.
  // Tier 1 swing models are too aggressive for counter-trend retracement entries.
  let candidates = MODELS;
  if (ctx.scalpOnly) {
    candidates = MODELS.filter(m => m.tier >= 2);
  }
  const results = candidates.map(m => evaluateModel(m, ctx));

  // ═══ WP-17: Pool-First Filtering ═══
  // When a session pool IS locked (raided + MSS confirmed), models that oppose the
  // locked direction are excluded from the complete set. ICT: "The pool IS the
  // trade idea. You don't fade the locked pool."
  let complete = results.filter(r => r.complete);
  let poolFiltered = false;
  const pc = ctx.poolContext;
  if (pc?.locked && pc.lockedDirection) {
    const before = complete.length;
    complete = complete.filter(r => {
      // Only keep models whose pool direction matches or is neutral toward the lock
      const dir = r.pool?.score >= 1.0 || !r.pool?.penalty;
      return dir;
    });
    if (complete.length < before) {
      poolFiltered = true;
    }
  }

  const confluence = confluenceOf(results, ctx);
  const completeDirs = [...new Set(complete
    .map(r => {
      const m = MODELS.find(x => x.id === r.id);
      return m ? effectiveDirection(m, ctx) : null;
    })
    .filter(Boolean))];

  let primary = null;
  let verdict = "NO TRADE";
  let confidence = null;

  if (complete.length > 0) {
    if (completeDirs.length === 1) {
      // One direction holds every complete setup → the clear winner. Ties within
      // that direction resolve by tier/draw; the rest stack as confluence.
      complete.sort((a, b) => tieBreak(a, b, ctx));
      primary = complete[0];
      verdict = "SETUP COMPLETE";
      confidence = confidenceOf(completeDirs[0], confluence);
    } else {
      // Complete setups on BOTH sides → genuine conflict → fail closed.
      verdict = "NO TRADE";
    }
  }

  // WP-16: Bayesian ML probability injection — posterior mean + credible interval
  let mlProbability = null;
  let mlConfidence = null;
  let expectedValue = null;

  if (primary) {
    const bayes = bayesianWR(primary.name);
    const ml = mlWeights[primary.name];

    if (bayes && ml) {
      // Bayesian 90% credible interval (using Normal approximation of Beta)
      const ci90Low = Math.max(0, bayes.posteriorMean - 1.645 * bayes.posteriorSD);
      const ci90High = Math.min(1, bayes.posteriorMean + 1.645 * bayes.posteriorSD);

      mlProbability = {
        model: primary.name,
        win_rate_pct: Math.round(bayes.posteriorMean * 1000) / 10,        // Bayesian posterior mean
        raw_win_rate_pct: Math.round(bayes.rawWR * 1000) / 10,            // raw empirical
        ci90_low: Math.round(ci90Low * 1000) / 10,                       // 90% credible interval
        ci90_high: Math.round(ci90High * 1000) / 10,
        samples: bayes.samples,
        precision: Math.round(bayes.precision * 100) / 100,              // 0-1 precision score
        calibration: ml.calibration || "UNKNOWN",
        recommendation: ml.recommendation || "NEUTRAL",
        prior: "Beta(5,5) — weak prior centered at 50%",
      };

      // Precision-weighted confidence blend
      // When precision is low (wide CI), the registry dominates
      // When precision is high (tight CI), the ML dominates
      const mlWeight = bayes.precision;          // 0 = no info, 1 = very precise
      const regWeight = 1.0 - mlWeight;
      const regConf = confidence || 0.5;
      const mlEstimate = bayes.posteriorMean;
      mlConfidence = Math.round((regConf * regWeight + mlEstimate * mlWeight) * 100) / 100;

      // Expected Value using Bayesian posterior mean
      const pWin = bayes.posteriorMean;
      const pLoss = 1 - pWin;
      const avgR = 1.5; // conservative — actual R:R from entry plan overrides
      const evR = pWin * avgR - pLoss;
      expectedValue = {
        p_win: Math.round(pWin * 100) / 100,
        p_loss: Math.round(pLoss * 100) / 100,
        ev_r: Math.round(evR * 100) / 100,
        interpretation: evR > 0.05 ? "POSITIVE_EDGE" : evR > -0.05 ? "NEAR_ZERO" : "NEGATIVE_EDGE",
        bayesian: true,
        prior: "Beta(5,5)",
        posterior_samples: bayes.samples + 10,
        note: "EV uses Bayesian posterior mean. Prior: Beta(5,5) centered at 50% WR. The prior shrinks the estimate toward 50% when samples are small — protecting against overfitting on thin data.",
      };
    } else if (ml) {
      // Fallback when Bayesian computation fails
      mlProbability = {
        model: primary.name,
        win_rate_pct: ml.win_rate_pct || 0,
        samples: ml.samples || 0,
        calibration: ml.calibration || "UNKNOWN",
        recommendation: ml.recommendation || "NEUTRAL",
      };
    }
  }

  return {
    verdict,
    primary,
    complete,
    count: complete.length,
    results,
    confluence,
    confidence,
    direction: completeDirs.length === 1 ? completeDirs[0] : null,
    mlProbability,
    mlConfidence,
    expectedValue,
    resolved: {
      tie: complete.length > 1,
      conflict: complete.length > 1 && completeDirs.length > 1,
      poolFiltered,
      poolLocked: pc?.locked || false,
      lockedDirection: pc?.lockedDirection || null,
      rule: "WP-17 Pool-First: locked pool (raided+MSS) sets direction priority. Models targeting the locked pool win ties. Models opposing the locked pool are excluded. One Trade Setup drives the registry.",
    },
  };
}

module.exports = {
  MODELS,
  inModelWindow,
  directionAligned,
  eligibilityOf,
  sequenceOf,
  evaluateModel,
  runRegistry,
  ALL_STEP_NAMES,
};
